#!/bin/bash
wp --url=https://benhvien1a.com post create --post_name='benh-vien-1a-tinh-nguyen-tham-gia-tiem-vaccine-tai-san-bay-tan-son-nhat-tpho-chi-minh' --post_title='Bệnh viện 1A tình nguyện tham gia tiêm vaccine tại sân bay Tân Sơn Nhất TP.Hồ Chí Minh.' --post_status='publish' --post_date='2021-06-23' doc/tintuc/benh-vien-1a-tinh-nguyen-tham-gia-tiem-vaccine-tai-san-bay-tan-son-nhat-tpho-chi-minh.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-tuyen-bhyt-noi-tru-tuyen-tinh-trong-toan-quoc-tu-112021' --post_title='Thông tuyến BHYT nội trú tuyến tỉnh trong toàn quốc từ 1/1/2021' --post_status='publish' --post_date='2020-12-31' doc/tintuc/thong-tuyen-bhyt-noi-tru-tuyen-tinh-trong-toan-quoc-tu-112021.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='bao-cao-ket-qua-kiem-tra-benh-vien-nam-2019' --post_title='Báo cáo kết quả kiểm tra bệnh viện năm 2019' --post_status='publish' --post_date='2020-08-05' doc/tintuc/bao-cao-ket-qua-kiem-tra-benh-vien-nam-2019.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tap-huan-ky-nang-giao-tiep-thay-thuoc-voi-benh-nhan' --post_title='Tập huấn kỹ năng giao tiếp thầy thuốc với bệnh nhân' --post_status='publish' --post_date='2020-12-26' doc/tintuc/tap-huan-ky-nang-giao-tiep-thay-thuoc-voi-benh-nhan.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-tuyen-dung-vien-chuc-nam-2020' --post_title='Thông báo tuyển dụng viên chức năm 2020' --post_status='publish' --post_date='2020-10-26' doc/tintuc/thong-bao-tuyen-dung-vien-chuc-nam-2020.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tphcm-huong-dan-cach-ly-cho-nguoi-lien-quan-ca-benh-o-hai-duong-quang-ninh' --post_title='TP.HCM hướng dẫn cách ly cho người liên quan ca bệnh ở Hải Dương, Quảng Ninh' --post_status='publish' --post_date='2021-01-29' doc/tintuc/tphcm-huong-dan-cach-ly-cho-nguoi-lien-quan-ca-benh-o-hai-duong-quang-ninh.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tiep-suc-cho-sinh-vien-tinh-nguyen-phong-chong-covid-19' --post_title='Tiếp sức cho sinh viên tình nguyện phòng chống covid-19' --post_status='publish' --post_date='2021-06-30' doc/tintuc/tiep-suc-cho-sinh-vien-tinh-nguyen-phong-chong-covid-19.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='khai-giang-khoa-hoc-more-than-words-nhieu-hon-loi-noi-thang-122020-va-012021' --post_title='KHAI GIẢNG KHÓA HỌC MORE THAN WORDS- NHIỀU HƠN LỜI NÓI THÁNG 12/2020 và 01/2021' --post_status='publish' --post_date='2020-12-10' doc/tintuc/khai-giang-khoa-hoc-more-than-words-nhieu-hon-loi-noi-thang-122020-va-012021.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='truc-tiep-benh-vien-1a-chia-lua-cung-sai-gon' --post_title='Trực tiếp: bệnh viện 1a“ chia lửa” cùng sài gòn' --post_status='publish' --post_date='2021-06-24' doc/tintuc/truc-tiep-benh-vien-1a-chia-lua-cung-sai-gon.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-chieu-sinh-lop-dieu-tri-tac-tuyen-sua' --post_title='Thông báo chiêu sinh lớp điều trị tắc tuyến sữa' --post_status='publish' --post_date='2020-12-17' doc/tintuc/thong-bao-chieu-sinh-lop-dieu-tri-tac-tuyen-sua.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-tuyen-dung-10-dieu-duong' --post_title='Thông báo tuyển dụng 10 điều dưỡng' --post_status='publish' --post_date='2021-03-12' doc/tintuc/thong-bao-tuyen-dung-10-dieu-duong.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='le-ky-niem-37-nam-thanh-lap-benh-vien-chinh-hinh-va-phuc-hoi-chuc-nang-tp-hcm' --post_title='Lễ kỷ niệm 37 năm thành lập bệnh viện chỉnh hình và phục hồi chức năng tp hcm' --post_status='publish' --post_date='2020-11-10' doc/tintuc/le-ky-niem-37-nam-thanh-lap-benh-vien-chinh-hinh-va-phuc-hoi-chuc-nang-tp-hcm.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tap-phuc-hoi-chuc-nang-cho-tre-em-bi-bai-nao-co-rut-got-chan' --post_title='Tập phục hồi chức năng cho trẻ em bị bại não, co rút gót chân.' --post_status='publish' --post_date='2021-05-14' doc/tintuc/tap-phuc-hoi-chuc-nang-cho-tre-em-bi-bai-nao-co-rut-got-chan.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dich-vu-test-nhanh-sars-covid-tai-benh-vien-1a' --post_title='Dịch vụ test nhanh sars-covid tại bệnh viện 1a' --post_status='publish' --post_date='2021-07-09' doc/tintuc/dich-vu-test-nhanh-sars-covid-tai-benh-vien-1a.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tan-man-chieu-cuoi-nam-2020' --post_title='Tản mạn chiều cuối năm 2020' --post_status='publish' --post_date='2020-12-31' doc/tintuc/tan-man-chieu-cuoi-nam-2020.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='can-bo-cong-nhan-vien-benh-vien-1a-tiem-du-2-lieu-vaccien-astra-zeneca' --post_title='Cán bộ công nhân viên Bệnh viện 1A tiêm đủ 2 liều vaccien Astra Zeneca' --post_status='publish' --post_date='2021-06-23' doc/tintuc/can-bo-cong-nhan-vien-benh-vien-1a-tiem-du-2-lieu-vaccien-astra-zeneca.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tuyen-dung-5-nhan-vien-truyen-thong-cskh' --post_title='Tuyển dụng 5 nhân viên truyền thông cskh' --post_status='future' --post_date='2021-03-23' doc/tintuc/tuyen-dung-5-nhan-vien-truyen-thong-cskh.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='can-hieu-dung-ve-muc-huong-100-chi-phi-kham-chua-benh-bhyt' --post_title='Cần hiểu đúng về mức hưởng 100% chi phí khám chữa bệnh BHYT' --post_status='future' --post_date='2020-12-30' doc/tintuc/can-hieu-dung-ve-muc-huong-100-chi-phi-kham-chua-benh-bhyt.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-xet-tuyen-vien-chuc-vong-ii' --post_title='Thông báo xét tuyển viên chức vòng ii' --post_status='future' --post_date='2021-07-20' doc/tintuc/thong-bao-xet-tuyen-vien-chuc-vong-ii.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='nhung-chien-si-ao-trang-1a' --post_title='Những chiến sĩ áo trắng 1a' --post_status='future' --post_date='2021-06-24' doc/tintuc/nhung-chien-si-ao-trang-1a.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hoi-thi-tay-nghe-dieu-duong-gioi-quan-tan-binh-nam-2020-tai-benh-vien-1a' --post_title='Hội thi tay nghề điều dưỡng giỏi quận Tân Bình năm 2020 tại Bệnh viện 1A' --post_status='future' --post_date='2020-10-23' doc/tintuc/hoi-thi-tay-nghe-dieu-duong-gioi-quan-tan-binh-nam-2020-tai-benh-vien-1a.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='toa-dam-cap-nhat-kien-thuc-va-chia-se-kinh-nghiem-lam-sang-trong-tao-hinh-vung-co-chan-va-ban-chan-bang-vat-da' --post_title='Toạ đàm Cập nhật kiến thức và chia sẻ kinh nghiệm lâm sàng trong tạo hình vùng cổ chân và bàn chân bằng vạt da' --post_status='future' --post_date='2021-03-22' doc/tintuc/toa-dam-cap-nhat-kien-thuc-va-chia-se-kinh-nghiem-lam-sang-trong-tao-hinh-vung-co-chan-va-ban-chan-bang-vat-da.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hai-nguoi-hai-duong-va-quang-ninh-lay-nhiem-ncov-cong-dong' --post_title='Hai người Hải Dương và Quảng Ninh lây nhiễm nCoV cộng đồng' --post_status='future' --post_date='2021-01-28' doc/tintuc/hai-nguoi-hai-duong-va-quang-ninh-lay-nhiem-ncov-cong-dong.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='to-chuc-dai-hoi-dang-lan-thu-xi-nhiem-ky-2020-2025' --post_title='Tổ chức Đại hội Đảng lần thứ XI, nhiệm kỳ 2020-2025' --post_status='future' --post_date='2020-05-22' doc/tintuc/to-chuc-dai-hoi-dang-lan-thu-xi-nhiem-ky-2020-2025.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='chuong-trinh-kham-mien-phi-cho-benh-nhan-seo-bong-di-tat' --post_title='Chương trình khám miễn phí cho bệnh nhân sẹo bỏng, dị tật.' --post_status='future' --post_date='2021-05-12' doc/tintuc/chuong-trinh-kham-mien-phi-cho-benh-nhan-seo-bong-di-tat.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='khai-giang-khoa-hoc-more-than-words-nhieu-hon-loi-noi-thang-11122020' --post_title='Khai giảng khóa học more than words- nhiều hơn lời nói tháng 11,12/2020' --post_status='future' --post_date='2020-10-10' doc/tintuc/khai-giang-khoa-hoc-more-than-words-nhieu-hon-loi-noi-thang-11122020.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='bao-cao-ket-qua-tu-kiem-tra-danh-gia-clbv-nam-2020' --post_title='Báo cáo kết quả tự kiểm tra, đánh giá clbv năm 2020' --post_status='future' --post_date='2021-01-08' doc/tintuc/bao-cao-ket-qua-tu-kiem-tra-danh-gia-clbv-nam-2020.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-tuyen-dung-ho-ly' --post_title='Thông báo tuyển dụng hộ lý' --post_status='future' --post_date='2021-05-27' doc/tintuc/thong-bao-tuyen-dung-ho-ly.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-tuyen-dung-dieu-duong-da-khoa-va-dieu-duong-chuyen-nganh-gmhs' --post_title='Thông báo tuyển dụng điều dưỡng đa khoa và điều dưỡng chuyên ngành gmhs' --post_status='future' --post_date='2021-05-06' doc/tintuc/thong-bao-tuyen-dung-dieu-duong-da-khoa-va-dieu-duong-chuyen-nganh-gmhs.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='benh-vien-1a-xuat-quan-chi-vien-trung-tam-tam-than-thu-duc' --post_title='Bệnh viện 1a xuất quân chi viện trung tâm tâm thần thủ đức' --post_status='future' --post_date='2021-07-30' doc/tintuc/benh-vien-1a-xuat-quan-chi-vien-trung-tam-tam-than-thu-duc.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-tuyen-dung-vien-chuc-nam-2021' --post_title='Thông báo tuyển dụng viên chức năm 2021' --post_status='future' --post_date='2021-05-06' doc/tintuc/thong-bao-tuyen-dung-vien-chuc-nam-2021.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-slogan-chinh-thuc-cho-benh-vien-cac-khoa-phong' --post_title='Thông báo slogan chính thức cho bệnh viện, các khoa phòng' --post_status='future' --post_date='2021-01-08' doc/tintuc/thong-bao-slogan-chinh-thuc-cho-benh-vien-cac-khoa-phong.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='them-4-ca-covid-19-o-tp-hcm' --post_title='Thêm 4 ca Covid-19 ở TP HCM' --post_status='future' --post_date='2021-02-08' doc/tintuc/them-4-ca-covid-19-o-tp-hcm.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='sau-nghi-tet-nhung-ai-den-tphcm-phai-cach-ly-va-xet-nghiem' --post_title='Sau nghỉ Tết, những ai đến TP.HCM phải cách ly và xét nghiệm?' --post_status='future' --post_date='2021-02-17' doc/tintuc/sau-nghi-tet-nhung-ai-den-tphcm-phai-cach-ly-va-xet-nghiem.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='trung-thu-yeu-thuong-cho-cac-em-benh-nhan-dang-dieu-tri-hoc-tap-tai-benh-vien-1a' --post_title='Trung thu yêu thương cho các em bệnh nhân đang điều trị, học tập tại Bệnh viện 1A' --post_status='future' --post_date='2020-10-05' doc/tintuc/trung-thu-yeu-thuong-cho-cac-em-benh-nhan-dang-dieu-tri-hoc-tap-tai-benh-vien-1a.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hoi-thi-tay-nghe-dieu-duong-ky-thuat-vien-nam-2020' --post_title='Hội thi tay nghề điều dưỡng – kỹ thuật viên năm 2020' --post_status='future' --post_date='2021-01-20' doc/tintuc/hoi-thi-tay-nghe-dieu-duong-ky-thuat-vien-nam-2020.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tu-01012021tat-ca-nguoi-benh-deu-duoc-huong-100-theo-muc-quy-dinh-chi-phi-kham-chua-benh-bhyt-noi-tru-tai-benh-vien-1a' --post_title='Từ 01/01/2021tất cả người bệnh đều được hưởng 100% theo mức quy định chi phí khám chữa bệnh bhyt nội trú tại bệnh viện 1a.' --post_status='future' --post_date='2020-11-22' doc/tintuc/tu-01012021tat-ca-nguoi-benh-deu-duoc-huong-100-theo-muc-quy-dinh-chi-phi-kham-chua-benh-bhyt-noi-tru-tai-benh-vien-1a.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='bao-cao-ket-qua-tu-kiem-tra-danh-gia-clbv-6-thang-dau-nam-2020' --post_title='Báo cáo kết quả tự kiểm tra, đánh giá clbv 6 tháng đầu  năm 2020' --post_status='future' --post_date='2020-08-22' doc/tintuc/bao-cao-ket-qua-tu-kiem-tra-danh-gia-clbv-6-thang-dau-nam-2020.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='thong-bao-ket-qua-xet-tuyen-vien-chuc-2020' --post_title='Thông báo kết quả xét tuyển viên chức 2020' --post_status='future' --post_date='2020-12-18' doc/tintuc/thong-bao-ket-qua-xet-tuyen-vien-chuc-2020.txt --post_type='post' --post_category=65 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='to-chuc-giai-bong-da-mini-nhan-ngay-quoc-te-phu-nu-va-37-nam-thanh-lap-benh-vien-1a' --post_title='Tổ chức giải bóng đã mini nhân ngày quốc tế phụ nữ và 37 năm thành lập Bệnh viện 1A' --post_status='future' --post_date='2020-10-19' doc/tintuc/to-chuc-giai-bong-da-mini-nhan-ngay-quoc-te-phu-nu-va-37-nam-thanh-lap-benh-vien-1a.txt --post_type='post' --post_category=65 --post_author=8
