#!/bin/bash
wp --url=https://benhvien1a.com post create --post_name='dieu-tri-khop-gia-nhiem-trung-mat-doan-xuong-do-bien-chung-gay-xuong' --post_title='Điều trị khớp giả nhiễm trùng, mất đoạn xương do biến chứng gãy xương' --post_status='publish' --post_date='2021-07-27' doc/kienthuc/dieu-tri-khop-gia-nhiem-trung-mat-doan-xuong-do-bien-chung-gay-xuong.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='phuong-phap-moi-dieu-tri-viem-khop-dang-thap-bang-thuoc-sinh-hoc-entanercept' --post_title='Phương pháp mới điều trị viêm khớp dạng thấp bằng thuốc sinh học (Entanercept)' --post_status='publish' --post_date='2021-07-28' doc/kienthuc/phuong-phap-moi-dieu-tri-viem-khop-dang-thap-bang-thuoc-sinh-hoc-entanercept.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='gay-xuong-suon-trieu-chung-phuong-phap-dieu-tri' --post_title='Gãy xương sườn : Triệu chứng, phương pháp điều trị?' --post_status='publish' --post_date='2021-07-29' doc/kienthuc/gay-xuong-suon-trieu-chung-phuong-phap-dieu-tri.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='loet-ty-de-vung-cung-cut' --post_title='Loét tỳ đè vùng cùng cụt' --post_status='publish' --post_date='2021-07-30' doc/kienthuc/loet-ty-de-vung-cung-cut.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='nhung-thoi-quen-anh-huong-xau-den-he-co-xuong-khop' --post_title='Những thói quen ảnh hưởng xấu đến hệ cơ xương khớp' --post_status='publish' --post_date='2021-07-31' doc/kienthuc/nhung-thoi-quen-anh-huong-xau-den-he-co-xuong-khop.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='rach-sun-chem-khop-goi-va-dieu-tri' --post_title='Rách sụn chêm khớp gối và điều trị' --post_status='publish' --post_date='2021-08-01' doc/kienthuc/rach-sun-chem-khop-goi-va-dieu-tri.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='viem-gan-got-gan-achilles' --post_title='Viêm gân gót (gân Achilles)' --post_status='publish' --post_date='2021-08-02' doc/kienthuc/viem-gan-got-gan-achilles.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='huong-dan-phuong-phap-cham-soc-mom-cut' --post_title='Hướng dẫn phương pháp chăm sóc mỏm cụt' --post_status='publish' --post_date='2021-08-03' doc/kienthuc/huong-dan-phuong-phap-cham-soc-mom-cut.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tu-the-tot-trong-sinh-hoat-hang-ngay' --post_title='Tư thế tốt trong sinh hoạt hằng ngày' --post_status='publish' --post_date='2021-08-04' doc/kienthuc/tu-the-tot-trong-sinh-hoat-hang-ngay.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='4-dau-hieu-nhan-biet-som-benh-gut-tranh-de-lai-cac-hau-qua-khon-luong' --post_title='4 dấu hiệu nhận biết sớm bệnh gút- tránh để lại các hậu quả khôn lường' --post_status='publish' --post_date='2021-08-05' doc/kienthuc/4-dau-hieu-nhan-biet-som-benh-gut-tranh-de-lai-cac-hau-qua-khon-luong.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='viem-quanh-khop-vai-la-gi' --post_title='Viêm quanh khớp vai là gì?' --post_status='publish' --post_date='2021-08-06' doc/kienthuc/viem-quanh-khop-vai-la-gi.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='ung-dung-cham-cuu-dieu-tri-hoi-chung-co-vai-canh-tay' --post_title='Ứng dụng châm cứu điều trị hội chứng cổ-vai-cánh tay' --post_status='publish' --post_date='2021-08-07' doc/kienthuc/ung-dung-cham-cuu-dieu-tri-hoi-chung-co-vai-canh-tay.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dieu-tri-dau-khong-phau-thuat-cac-benh-lech-veo-cot-song' --post_title='Điều trị đau không phẫu thuật các bệnh lệch vẹo cột sống' --post_status='publish' --post_date='2021-08-08' doc/kienthuc/dieu-tri-dau-khong-phau-thuat-cac-benh-lech-veo-cot-song.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='huong-dan-bai-tap-cot-song-co' --post_title='Hướng dẫn bài tập cột sống cổ' --post_status='publish' --post_date='2021-08-09' doc/kienthuc/huong-dan-bai-tap-cot-song-co.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dung-thuoc-va-che-do-an-cho-nguoi-bi-benh-gout' --post_title='Dùng thuốc và chế độ ăn cho người bị bệnh gout' --post_status='publish' --post_date='2021-08-10' doc/kienthuc/dung-thuoc-va-che-do-an-cho-nguoi-bi-benh-gout.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='huong-dan-bai-tap-cho-benh-nhan-suy-gian-tinh-mach-chan' --post_title='Hướng dẫn bài tập cho bệnh nhân suy giãn tĩnh mạch chân' --post_status='future' --post_date='2021-08-11' doc/kienthuc/huong-dan-bai-tap-cho-benh-nhan-suy-gian-tinh-mach-chan.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tong-quan-ve-nang-nguc' --post_title='Tổng quan về nâng ngực' --post_status='future' --post_date='2021-08-12' doc/kienthuc/tong-quan-ve-nang-nguc.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='roi-loan-luong-cuc' --post_title='Rối loạn lưỡng cực' --post_status='future' --post_date='2021-08-13' doc/kienthuc/roi-loan-luong-cuc.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dut-day-chang-cheo-truoc-nhung-dieu-can-biet' --post_title='Đứt dây chằng chéo trước: những điều cần biết' --post_status='future' --post_date='2021-08-14' doc/kienthuc/dut-day-chang-cheo-truoc-nhung-dieu-can-biet.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='trieu-trung-dau-lung' --post_title='Triệu trứng đau lưng' --post_status='future' --post_date='2021-08-15' doc/kienthuc/trieu-trung-dau-lung.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dien-cham-dieu-tri-liet-nua-nguoi-do-tai-bien-mach-mau-nao' --post_title='Điện châm điều trị liệt nửa người do tai biến mạch máu não' --post_status='future' --post_date='2021-08-16' doc/kienthuc/dien-cham-dieu-tri-liet-nua-nguoi-do-tai-bien-mach-mau-nao.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='viem-mom-tren-loi-cau-xuong-canh-tay' --post_title='Viêm mỏm trên lồi cầu xương cánh tay' --post_status='future' --post_date='2021-08-17' doc/kienthuc/viem-mom-tren-loi-cau-xuong-canh-tay.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='anh-huong-cua-hoat-dong-the-duc-the-thao-trong-su-hinh-thanh-the-chat-va-nhan-cach-cua-tre-em' --post_title='Ảnh hưởng của hoạt động  thể dục thể thao trong sự hình thành  thể chất và nhân cách của trẻ em' --post_status='future' --post_date='2021-08-18' doc/kienthuc/anh-huong-cua-hoat-dong-the-duc-the-thao-trong-su-hinh-thanh-the-chat-va-nhan-cach-cua-tre-em.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='cac-chan-thuong-thuong-gap-trong-the-thao-va-nhung-dieu-can-biet' --post_title='Các chấn thương thường gặp trong thể thao và những điều cần biết' --post_status='future' --post_date='2021-08-19' doc/kienthuc/cac-chan-thuong-thuong-gap-trong-the-thao-va-nhung-dieu-can-biet.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='veo-cot-song-scoliosis--nguyen-nhan-va-cach-dieu-tri' --post_title='Vẹo cột sống (Scoliosis)- Nguyên nhân và cách điều trị' --post_status='future' --post_date='2021-08-20' doc/kienthuc/veo-cot-song-scoliosis--nguyen-nhan-va-cach-dieu-tri.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='huong-dan-tap-phuc-hoi-chuc-nang-sau-mo-thay-khop-goi' --post_title='Hướng dẫn tập phục hồi chức năng sau mổ thay khớp gối' --post_status='future' --post_date='2021-08-21' doc/kienthuc/huong-dan-tap-phuc-hoi-chuc-nang-sau-mo-thay-khop-goi.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='phuc-hoi-chuc-nang-liet-mat-liet-day-than-kinh-vii-ngoai-bien' --post_title='Phục hồi chức năng liệt mặt- liệt dây thần kinh vii ngoại biên' --post_status='future' --post_date='2021-08-22' doc/kienthuc/phuc-hoi-chuc-nang-liet-mat-liet-day-than-kinh-vii-ngoai-bien.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='ky-thuat-keo-gian-cot-song-bang-may-keo' --post_title='Kỹ thuật kéo giãn cột sống bằng máy kéo' --post_status='future' --post_date='2021-08-23' doc/kienthuc/ky-thuat-keo-gian-cot-song-bang-may-keo.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hoi-sinh-ngon-tay-bi-chem-dut-lia' --post_title='Hồi sinh ngón tay bị chém đứt lìa' --post_status='future' --post_date='2021-08-24' doc/kienthuc/hoi-sinh-ngon-tay-bi-chem-dut-lia.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='viem-khop-dang-thap' --post_title='Viêm khớp dạng thấp' --post_status='future' --post_date='2021-08-25' doc/kienthuc/viem-khop-dang-thap.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='cac-ky-thuat-trong-cham-soc-vet-thuong-ban-chan-dai-thao-duong' --post_title='Các kỹ thuật trong chăm sóc vết thương bàn chân đái tháo đường' --post_status='future' --post_date='2021-08-26' doc/kienthuc/cac-ky-thuat-trong-cham-soc-vet-thuong-ban-chan-dai-thao-duong.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='ung-dung-tri-tue-nhan-tao-ai-trong-quan-ly-chan-thuong-day-chang-cheo-truoc' --post_title='Ứng dụng trí tuệ nhân tạo (a.i.) trong quản lý chấn thương dây chằng chéo trước' --post_status='future' --post_date='2021-08-27' doc/kienthuc/ung-dung-tri-tue-nhan-tao-ai-trong-quan-ly-chan-thuong-day-chang-cheo-truoc.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='chinh-hinh-bien-dang-co-gap-goi-do-bong-khong-phau-thuat' --post_title='Chỉnh hình biến dạng co gấp gối do bỏng  không phẫu thuật' --post_status='future' --post_date='2021-08-28' doc/kienthuc/chinh-hinh-bien-dang-co-gap-goi-do-bong-khong-phau-thuat.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='5-bai-tap-phuc-hoi-chuc-nang-quan-trong-cho-nguoi-tai-bien' --post_title='5 bài tập phục hồi chức năng quan trọng cho người tai biến' --post_status='future' --post_date='2021-08-29' doc/kienthuc/5-bai-tap-phuc-hoi-chuc-nang-quan-trong-cho-nguoi-tai-bien.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='che-do-dinh-duong-va-theo-doi-cac-phan-ung-phu-khi-tiem-vac-xin-phong-covid-19' --post_title='Chế độ dinh dưỡng và theo dõi các phản ứng phụ khi tiêm Vắc xin phòng COVID- 19' --post_status='future' --post_date='2021-08-30' doc/kienthuc/che-do-dinh-duong-va-theo-doi-cac-phan-ung-phu-khi-tiem-vac-xin-phong-covid-19.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='nen-dung-ao-nep-hay-phau-thuat-de-dieu-tri-veo-cot-song' --post_title='Nên dùng áo nẹp hay phẫu thuật để điều trị vẹo cột sống?' --post_status='future' --post_date='2021-08-31' doc/kienthuc/nen-dung-ao-nep-hay-phau-thuat-de-dieu-tri-veo-cot-song.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tiem-steroid-ngoai-mang-cung-vung-cot-song-that-lung' --post_title='Tiêm steroid ngoài màng cứng  vùng cột sống thắt lưng' --post_status='future' --post_date='2021-09-01' doc/kienthuc/tiem-steroid-ngoai-mang-cung-vung-cot-song-that-lung.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='bieu-hien-lam-sang-va-chuan-doan-benh-gut' --post_title='Biểu hiện lâm sàng và chuẩn đoán bệnh gút' --post_status='future' --post_date='2021-09-02' doc/kienthuc/bieu-hien-lam-sang-va-chuan-doan-benh-gut.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='gay-xuong-cang-chan' --post_title='Gãy xương cẳng chân' --post_status='future' --post_date='2021-09-03' doc/kienthuc/gay-xuong-cang-chan.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='nhung-dieu-ban-can-biet-truoc-khi-thay-khop-hang-nhan-tao' --post_title='Những điều bạn cần biết trước khi thay khớp háng nhân tạo' --post_status='future' --post_date='2021-09-04' doc/kienthuc/nhung-dieu-ban-can-biet-truoc-khi-thay-khop-hang-nhan-tao.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='viem-gan-dai-co-nhi-dau-canh-tay' --post_title='Viêm gân dài cơ nhị đầu cánh tay' --post_status='future' --post_date='2021-09-05' doc/kienthuc/viem-gan-dai-co-nhi-dau-canh-tay.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='chinh-hinh-phuc-hoi-chuc-nang-cho-mom-cut-cang-chan-ngan-va-co-gap' --post_title='Chỉnh hình phục hồi chức năng cho mỏm cụt cẳng chân ngắn  và co gấp' --post_status='future' --post_date='2021-09-06' doc/kienthuc/chinh-hinh-phuc-hoi-chuc-nang-cho-mom-cut-cang-chan-ngan-va-co-gap.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='vai-tro-cua-icu-trong-cac-truong-hop-nguy-kich' --post_title='Vai trò của icu trong các trường hợp nguy kịch' --post_status='future' --post_date='2021-09-07' doc/kienthuc/vai-tro-cua-icu-trong-cac-truong-hop-nguy-kich.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dieu-tri-bao-ton-cho-tre-veo-cot-song-tu-phat' --post_title='Điều trị bảo tồn cho trẻ vẹo cột sống tự phát' --post_status='future' --post_date='2021-09-08' doc/kienthuc/dieu-tri-bao-ton-cho-tre-veo-cot-song-tu-phat.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='vai-tro-dau-an-chu-chuyen-xuong-bone-turnover-trong-theo-doi-dap-ung-dieu-tri-loang-xuong' --post_title='Vai trò dấu ấn chu chuyển xương (Bone Turnover) trong theo dõi đáp ứng điều trị loãng xương' --post_status='future' --post_date='2021-09-09' doc/kienthuc/vai-tro-dau-an-chu-chuyen-xuong-bone-turnover-trong-theo-doi-dap-ung-dieu-tri-loang-xuong.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hoai-tu-vo-khuan-chom-xuong-dui--chan-doan-dieu-tri' --post_title='Hoại tử vô khuẩn chỏm xương đùi- chẩn đoán, điều trị' --post_status='future' --post_date='2021-09-10' doc/kienthuc/hoai-tu-vo-khuan-chom-xuong-dui--chan-doan-dieu-tri.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='lua-chon-manh-ghep-cho-tai-tao-day-chang-cheo-truoc' --post_title='Lựa chọn mảnh ghép cho tái tạo dây chằng chéo trước' --post_status='future' --post_date='2021-09-11' doc/kienthuc/lua-chon-manh-ghep-cho-tai-tao-day-chang-cheo-truoc.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='trat-khop-vai-tai-dien' --post_title='Trật khớp vai tái diễn' --post_status='future' --post_date='2021-09-12' doc/kienthuc/trat-khop-vai-tai-dien.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='viem-gan-vung-mom-cham-quay-hoi-chung-de-quervain' --post_title='Viêm gân vùng mỏm châm quay (Hội chứng De Quervain)' --post_status='future' --post_date='2021-09-13' doc/kienthuc/viem-gan-vung-mom-cham-quay-hoi-chung-de-quervain.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='phuc-hoi-chuc-nang-sau-phau-thuat-mo-noi-soi-gan-co-chop-xoay' --post_title='Phục hồi chức năng sau phẫu thuật mổ nội soi gân cơ chóp xoay' --post_status='future' --post_date='2021-09-14' doc/kienthuc/phuc-hoi-chuc-nang-sau-phau-thuat-mo-noi-soi-gan-co-chop-xoay.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='phuc-hoi-chuc-nang-sau-phau-thuat-noi-soi-tai-tao-day-chang-cheo-truoc-su-dung-manh-ghep-gan-hamstring' --post_title='Phục hồi chức năng sau phẫu thuật nội soi tái tạo dây chằng chéo trước sử dụng mảnh ghép gân hamstring' --post_status='future' --post_date='2021-09-15' doc/kienthuc/phuc-hoi-chuc-nang-sau-phau-thuat-noi-soi-tai-tao-day-chang-cheo-truoc-su-dung-manh-ghep-gan-hamstring.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dieu-tri-cac-khuyet-hong-phan-mem-vung-cang-ban-chan' --post_title='Điều trị các khuyết hổng phần mềm vùng cẳng bàn chân' --post_status='future' --post_date='2021-09-16' doc/kienthuc/dieu-tri-cac-khuyet-hong-phan-mem-vung-cang-ban-chan.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='gay-xuong-thuyen' --post_title='Gãy xương thuyền' --post_status='future' --post_date='2021-09-17' doc/kienthuc/gay-xuong-thuyen.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='vai-tro-cua-dung-cu-chinh-hinh' --post_title='Vai trò của dụng cụ chỉnh hình' --post_status='future' --post_date='2021-09-18' doc/kienthuc/vai-tro-cua-dung-cu-chinh-hinh.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='gay-lien-mau-chuyen-xuong-dui' --post_title='Gãy liên máu chuyển xương đùi' --post_status='future' --post_date='2021-09-19' doc/kienthuc/gay-lien-mau-chuyen-xuong-dui.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='diec-dot-ngot-va-hieu-qua-dieu-tri-bang-oxy-cao-ap' --post_title='Điếc đột ngột và hiệu quả điều trị bằng oxy cao áp' --post_status='future' --post_date='2021-09-20' doc/kienthuc/diec-dot-ngot-va-hieu-qua-dieu-tri-bang-oxy-cao-ap.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hoai-tu-vo-khuan-chom-xuong-dui-o-tre-em-legg-calve-perthes' --post_title='Hoại tử vô khuẩn chỏm xương đùi ở trẻ em (legg-calve-perthes)' --post_status='future' --post_date='2021-09-21' doc/kienthuc/hoai-tu-vo-khuan-chom-xuong-dui-o-tre-em-legg-calve-perthes.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='benh-viem-quanh-khop-vai-o-nguoi-cao-tuoi' --post_title='Bệnh viêm quanh khớp vai ở người cao tuổi' --post_status='future' --post_date='2021-09-22' doc/kienthuc/benh-viem-quanh-khop-vai-o-nguoi-cao-tuoi.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='huong-dan-tap-cot-song-that-lung' --post_title='Hướng dẫn tập cột sống thắt lưng' --post_status='future' --post_date='2021-09-23' doc/kienthuc/huong-dan-tap-cot-song-that-lung.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dieu-tri-ngan-chi-duoi-o-tre-em-bang-keo-dai-chi' --post_title='Điều trị ngắn chi dưới ở trẻ em bằng kéo dài chi' --post_status='future' --post_date='2021-09-24' doc/kienthuc/dieu-tri-ngan-chi-duoi-o-tre-em-bang-keo-dai-chi.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='giam-rui-ro-phai-cat-chan-cho-nguoi-tieu-duong' --post_title='Giảm rủi ro phải cắt chân cho người tiểu đường' --post_status='future' --post_date='2021-09-25' doc/kienthuc/giam-rui-ro-phai-cat-chan-cho-nguoi-tieu-duong.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dau-than-kinh-toa' --post_title='Đau thần kinh tọa' --post_status='future' --post_date='2021-09-26' doc/kienthuc/dau-than-kinh-toa.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='gay-xuong-banh-che' --post_title='Gãy xương bánh chè' --post_status='future' --post_date='2021-09-27' doc/kienthuc/gay-xuong-banh-che.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='phan-loai-benh-khop' --post_title='Phân loại bệnh khớp' --post_status='future' --post_date='2021-09-28' doc/kienthuc/phan-loai-benh-khop.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='bai-tap-cho-benh-nhan-sau-phau-thuat-tai-tao-day-chang-cheo-truoc' --post_title='Bài tập cho bệnh nhân sau phẫu thuật tái tạo dây chằng chéo trước' --post_status='future' --post_date='2021-09-29' doc/kienthuc/bai-tap-cho-benh-nhan-sau-phau-thuat-tai-tao-day-chang-cheo-truoc.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dung-cu-phau-thuat-hien-dai-vu-khi-giup-cac-ca-phau-thuat-thanh-cong' --post_title='Dụng cụ phẫu thuật hiện đại, vũ khí giúp các ca phẫu thuật thành công' --post_status='future' --post_date='2021-09-30' doc/kienthuc/dung-cu-phau-thuat-hien-dai-vu-khi-giup-cac-ca-phau-thuat-thanh-cong.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='phau-thuat-xam-lan-toi-thieu-phuong-phap-toi-uu-trong-dieu-tri-benh-ly-cot-song' --post_title='Phẫu thuật xâm lấn tối thiểu – phương pháp tối ưu trong điều trị bệnh lý cột sống' --post_status='future' --post_date='2021-10-01' doc/kienthuc/phau-thuat-xam-lan-toi-thieu-phuong-phap-toi-uu-trong-dieu-tri-benh-ly-cot-song.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hoi-chung-suon-don' --post_title='Hội chứng sườn đòn' --post_status='future' --post_date='2021-10-02' doc/kienthuc/hoi-chung-suon-don.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='phuc-hoi-chuc-nang-sau-phau-thuat-thay-khop-hang' --post_title='Phục hồi chức năng sau phẫu thuật thay khớp háng' --post_status='future' --post_date='2021-10-03' doc/kienthuc/phuc-hoi-chuc-nang-sau-phau-thuat-thay-khop-hang.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='benh-loan-duong-co' --post_title='Bệnh loạn dưỡng cơ' --post_status='future' --post_date='2021-10-04' doc/kienthuc/benh-loan-duong-co.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='loang-xuong-o-phu-nu-sau-man-kinh' --post_title='Loãng xương ở phụ nữ sau mãn kinh' --post_status='future' --post_date='2021-10-05' doc/kienthuc/loang-xuong-o-phu-nu-sau-man-kinh.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='hoi-chung-tennis-elbow-qua-lang-kinh-y-hoc-the-thao' --post_title='Hội chứng tennis elbow qua lăng kính y học thể thao' --post_status='future' --post_date='2021-10-06' doc/kienthuc/hoi-chung-tennis-elbow-qua-lang-kinh-y-hoc-the-thao.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dieu-tri-khuyet-da-mu-chan-do-ung-thu-da-bang-vat-tren-mat-ca-ngoai' --post_title='Điều trị khuyết da mu chân do ung thư da bằng vạt trên mắt cá ngoài' --post_status='future' --post_date='2021-10-07' doc/kienthuc/dieu-tri-khuyet-da-mu-chan-do-ung-thu-da-bang-vat-tren-mat-ca-ngoai.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='huong-dan-bai-tap-cot-song-that-lung-cot-song-co' --post_title='Hướng dẫn bài tập cột sống thắt lưng, cột sống cổ' --post_status='future' --post_date='2021-10-08' doc/kienthuc/huong-dan-bai-tap-cot-song-that-lung-cot-song-co.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='dieu-tri-bang-dien' --post_title='Điều trị bằng Điện' --post_status='future' --post_date='2021-10-09' doc/kienthuc/dieu-tri-bang-dien.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='tam-quan-trong-cua-viec-kham-suc-khoe-dinh-ky' --post_title='Tầm quan trọng của việc khám sức khỏe định kỳ' --post_status='future' --post_date='2021-10-10' doc/kienthuc/tam-quan-trong-cua-viec-kham-suc-khoe-dinh-ky.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='viem-xuong-chan-thuong' --post_title='Viêm xương chấn thương' --post_status='future' --post_date='2021-10-11' doc/kienthuc/viem-xuong-chan-thuong.txt --post_type='post' --post_category=61 --post_author=8
wp --url=https://benhvien1a.com post create --post_name='nhung-dieu-ban-can-biet-truoc-khi-thay-khop-goi-nhan-tao' --post_title='Những điều bạn cần biết trước khi thay khớp gối nhân tạo' --post_status='future' --post_date='2021-10-12' doc/kienthuc/nhung-dieu-ban-can-biet-truoc-khi-thay-khop-goi-nhan-tao.txt --post_type='post' --post_category=61 --post_author=8
